### ISSUE TITLE
Boxes sometimes flickering in TouchDesigner 

### ISSUE THREAD

**Issue by omansounds** [KernelA/yolo-video-detection-example#17]
Hello,

First off, amazing work! I have been trying to find a way to implement Yolov8 in TouchDesigner for some time now. 

My issue is that when I open TouchDesigner after executing the processing file, the boxes sometimes do not appear. If I adjust the threshold, the boxes will flicker on and off until I stop moving it. Sometimes, however, when I open TouchDesigner, everything works fine and the boxes show with the labels and score. 

I was curious if you have any resolutions for this issue? Let me know if I am not being clear enough and I can add more detail.

Thanks

https://github.com/KernelA/yolo-video-detection-example/assets/120405753/a16194da-aff6-468e-9106-7e154d98af44

**Comment by KernelA** [comment]
Hi, @omansounds. 

I think there are two reasons:

1. Threshold is the confidence level of the model. At some level, all detected objects do not satisfy the level and will be filtered. This repository contains a simple example without tracking. In some cases, an object can be lost on the next frame.
2. The current solution is not stable because there are shared memory boolean flags, and it can lead to bugs in processing. Simple solution here is close TouchDesigner, restarting `processing.py` and open TouchDesigner.

**Comment by omansounds** [comment]
Thank you for the response. Is it possible to send the processing data into TouchDesigner as well?

I would love to talk with you about this project in more depth if you have time. My email is connor@omansounds.com. I can compensate for your time.
